---
title: "Stat approaches for network generation"
format: html
editor: visual
---

# Libraries

```{r Libraries}
library(openxlsx)
library(here)
library(limma)
library(dplyr)
library(tibble)
library(janitor)
library(ggplot2)
library(rbioapi)
library(OmnipathR)
library(purrr)
library(org.Hs.eg.db)
library(clusterProfiler)
library(stringr)
```

# Loading tables from QproMS

(BH, no correction and imputed table). BH and no correction were ready for further analysis, whereas the imputed table was used to perform LIMMA statistical approach. Another table was analysed on Perseus (doing permutation).

```{r Loading table}
protein_groups <- data.table::fread(here::here("proteinGroups_sqstm1.txt")) %>% 
  janitor::clean_names() %>% 
  dplyr::filter(potential_contaminant!="+" & only_identified_by_site!="+" & reverse!="+" ) %>% 
  dplyr::select(gene_names, intensity) %>% 
  dplyr::mutate(intensity=log2(intensity)) %>% 
  dplyr::mutate(intensity=dplyr::na_if(intensity, -Inf))
  


welch_bh <-
  openxlsx::read.xlsx(xlsxFile = "/Users/giorgiacucina/QProMS_functions.git/Univariate_table_2023-09-19.xlsx") %>%
  dplyr::filter(apexp62_vs_apexonly_significant) %>%
  dplyr::filter(apexp62_vs_apexonly_fold_change > 0)


welch_none <-
  openxlsx::read.xlsx(xlsxFile = "/Users/giorgiacucina/QProMS_functions.git/none_adj_Univariate_table_2023-09-19.xlsx") %>%
  dplyr::filter(apexp62_vs_apexonly_significant) %>%
  dplyr::filter(apexp62_vs_apexonly_fold_change > 0)

limma <- openxlsx::read.xlsx(xlsxFile = "/Users/giorgiacucina/QProMS_functions.git/Imputed_table_2023-09-19.xlsx")

perseus <-
  data.table::fread(file = "/Users/giorgiacucina/QProMS_functions.git/welch_permutation.txt", sep = "\t") %>%
  janitor::clean_names() %>%
  dplyr::select(dplyr::contains("apex"), gene_names) %>%
  dplyr::slice(3:n()) %>%
  dplyr::filter(welchs_t_test_significant_apexonly_apexp62 == "+") %>%
  dplyr::filter(welchs_t_test_difference_apexonly_apexp62 < 0) %>% #abbiamo sbagliato il confronto, quindi le negative sono quelle di interesse
  dplyr::mutate(gene_names = sub(";.*", "", gene_names)) %>%
  dplyr::select(gene_names, p_val = log_welchs_t_test_p_value_apexonly_apexp62, log_fc =
                  welchs_t_test_difference_apexonly_apexp62) 
  # write.table(file = "/Users/giorgiacucina/Desktop/perseus_nodes.txt")
  
```

# LIMMA

```{r LIMMA}
limma_matrix <-
  limma %>% tibble::column_to_rownames("gene_names") %>%
  as.matrix()

group_list <- factor(x=c("apex","apex","apex","apex","apex", "only","only","only","only","only"), levels = c("apex", "only"))

design <- model.matrix(~group_list)
limma_fit <- limma::lmFit(limma_matrix, design) 
fit <- eBayes(limma_fit)
limma_tibble<- topTable(fit, number = nrow(limma)) %>% tibble::rownames_to_column("gene_names") %>%
  dplyr::filter(adj.P.Val<0.05) %>% 
  dplyr::filter(logFC>0) %>% 
  dplyr::mutate(p_adj= -log10(adj.P.Val)) %>% 
  dplyr::mutate(gene_names= stringr::str_replace(gene_names, "_.*", ""))

 # limma_tibble %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_nodes.txt",quote = FALSE,sep = "\t", row.names = FALSE)
```

# STRING db

```{r Stringdb upload}
gene_names <- data.table::fread(here::here("9606.protein.info.v11.5.txt")) %>% 
  dplyr::select(string_protein_id, preferred_name)

human_string <- data.table::fread(here::here("9606.protein.links.v11.5.txt")) %>% 
  dplyr::mutate(combined_score= combined_score/1000) %>% 
  dplyr::left_join(gene_names, by=c("protein1" = "string_protein_id")) %>%
  dplyr::rename("source"="preferred_name") %>% 
  dplyr::left_join(gene_names, by=c("protein2" = "string_protein_id")) %>% 
  dplyr::rename("target"="preferred_name") %>% 
  dplyr::select(source, target, combined_score)
```

```{r All the functions}
string_find_interactors <- function(table, score=400, limits=NULL) {
  
  gene_list <- table %>%
    dplyr::pull(gene_names)
  
  data <-
    rba_string_interaction_partners(
      ids = gene_list,
      species = 9606,
      required_score = score,
      limit = limits
    ) %>%
    dplyr::select(source = preferredName_A, target = preferredName_B, score) %>% #Real vs predicted instead of source and target
    unique() # GUARDA QUI
  return(data)
}

predicted_node_table <- function(predicted_table_interactors, table) {
  predict <- predicted_table_interactors %>%
    dplyr::count(target) %>%
    pull(target)
  
  sperimental <- table %>%
    pull(gene_names)
  
  nodes_predicted_all <- c(predict, sperimental)
  
  nodes_predicted <- unique(nodes_predicted_all)
  
  return(nodes_predicted)
}

corum_edges <- function(predicted_list) {

raw_corum_table <-
    get_complex_genes(import_omnipath_complexes(resources = "CORUM"),
                      predicted_list,
                      total_match = FALSE) %>%
    unique() %>%
    dplyr::select(name, components_genesymbols) %>%
    tidyr::separate_rows(components_genesymbols, sep = "_") %>%
    dplyr::filter(components_genesymbols %in% predicted_list) %>% #Potremmo voler tenere i nodi di corum che non sono nella nostra lista?
    unique() %>% 
    get_dupes(name)

    expand_nodes <- raw_corum_table %>%
      dplyr::group_by(name) %>%
      dplyr::group_map( ~ dplyr::pull(.x, components_genesymbols)) 
    
    edges_corum_table <-
      purrr::map(.x = expand_nodes, .f = ~ as.data.frame(t(combn(.x, 2)))) %>% 
      purrr::reduce(dplyr::bind_rows) %>% 
      dplyr::rename(target = V1,  source = V2) %>%
      dplyr::left_join(raw_corum_table, by = c("source" = "components_genesymbols")) %>% 
      dplyr::select(-dupe_count) %>% 
      dplyr::select(source, target) %>%
      unique() %>% 
      dplyr::mutate(source_target = paste0(source, "_", target)) %>%
      dplyr::mutate(target_source = paste0(target, "_", source))
    
    return(edges_corum_table)
}

roc_precision_data <- function(corum_table, string_predicted_interactors) {
  
    data <- string_predicted_interactors %>%
      dplyr::mutate(
        corum = case_when(
          source_target %in% corum_table$source_target ~ 1,
          source_target %in% corum_table$target_source ~ 1,
          TRUE ~ 0
        )
      )
    
    df <- tibble::tibble()
    
    for (i in seq(from = 1, to = 0, by = -0.10)) {
      string_thr <- data %>%
        dplyr::mutate(thr = if_else(score >= i, "yes", "no")) #Vedo quali interazioni di String sono anche in CORUM (TP)
      
      for (j in 1:10) {
        set.seed(j)
        source <-
          sample(
            string_thr$source,
            size = sum(string_thr$corum == 1),
            replace = TRUE
          )
        target <-
          sample(
            string_thr$target,
            size = sum(string_thr$corum == 1),
            replace = TRUE
          )
        
        random_int <- cbind(source, target) %>%
          as.data.frame() %>%
          dplyr::left_join(human_string, by = join_by(source, target)) %>%
          dplyr::mutate(score = dplyr::if_else(is.na(combined_score), 0, combined_score)) %>% 
          dplyr::select(-combined_score)
        
        df_1 <-
          tibble::tibble(
                    TP = sum(string_thr$thr == "yes" & string_thr$corum == 1),
                    FN = sum(string_thr$thr == "no" & string_thr$corum == 1),
                    TPR = TP / (TP + FN),
                    FP = sum(random_int$score >= i),
                    TN = sum(random_int$score < i),
                    FPR = FP / (FP + TN),
                    STRINGSCORE = i,
                    fold = j
                  )  
        
        df <- rbind(df, df_1)
        
      }
    }
    
    
    df_final <- df %>%
      dplyr::mutate(P = TP / (TP + FP)) %>%
      dplyr::group_by(STRINGSCORE) %>%
      dplyr::summarise(
        FPR_mean = mean(FPR),
        FPR_sd = sd(FPR),
        TPR_mean = mean(TPR),
        TPR_sd = sd(TPR),
        P_mean = mean(P),
        P_sd = sd(P)
      ) 
    return(df_final)
        print(df_final)
}

roc_precision_graph <- function(data, graph) {
  if (graph=="roc") {
    p1 <- ggplot2::ggplot(data, aes(
      x = FPR_mean,
      y = TPR_mean,
      color = as.factor(STRINGSCORE)
    )) +
      geom_point() +
      geom_line()+
      labs(x = "False Positive Rate",
           y = "True Positive Rate",
           title = "ROC Curve")  +
      geom_abline(slope = 1, linetype = "dashed") +
      geom_errorbar(aes(xmin = FPR_mean - FPR_sd,
                        xmax = FPR_mean + FPR_sd),
                    color = "black") +
      geom_rect(aes(
        xmin = 0,
        xmax = 0.2,
        ymin = 0.7,
        ymax = 1
      ),
      color = "darkgrey",
      alpha = 0)
    
    p2 <- ggplot2::ggplot(data, aes(
      x = FPR_mean,
      y = TPR_mean,
      color = as.factor(STRINGSCORE)
    )) +
      geom_point() +
        geom_errorbar(aes(xmin = FPR_mean - FPR_sd,
                        xmax = FPR_mean + FPR_sd),
                    color = "black")+
  xlim(0, 0.2)+
  ylim(0.7, 1)+
  theme_bw() +
  theme(
    axis.title = element_blank(), legend.position = "none"
  )
    p<- p1 + 
  # xmin, xmax, ymin, ymax represent the position and dimension of the zoomed plot
  annotation_custom(ggplotGrob(p2), xmin = 0.6, xmax = 1, ymin = 0, ymax = 0.5) +
  # this geom_rect() draws the border dashed line of the zoomed plot
  geom_rect(aes(xmin = 0.6, xmax = 1, ymin = 0, ymax = 0.5), color='darkgrey', alpha=0)
      
  }else {
    p <- ggplot2::ggplot(data, aes(
      x = TPR_mean,
      y = P_mean,
      color = as.factor(STRINGSCORE)
    )) +
      geom_point() +
      geom_errorbar(aes(ymin = P_mean - P_sd,
                        ymax = P_mean + P_sd),
                    color = "black") +
      labs(x = "Recall",
           y = "Precision",
           title = "Precision-Recall Curve")
  }
  
  p<-p +
    geom_line(color = "black") +
      guides(color = guide_legend(title = "StringScore")) +
      ylim(0, 1) +
      xlim(0, 1) +
  theme_bw()
  return(p)
}

enrichment_table <- function(predicted_table_interactors, thr, simplify_thr, table) {
  
  roc_filtered <- predicted_table_interactors %>% 
    dplyr::filter(score>=thr) %>% 
    dplyr::count(target) %>%
    pull(target)
  
  sperimental <- table %>%
    pull(gene_names)
  
  nodes_predicted_all <- c(roc_filtered, sperimental)
  
  nodes_roc_filtered <- unique(nodes_predicted_all)
  
  enrich <-
    enrichGO(nodes_roc_filtered,
      OrgDb = org.Hs.eg.db,
      keyType= "SYMBOL",
      ont = "CC",
      pAdjustMethod = "BH",
      pvalueCutoff = 0.05
    ) %>%
    setReadable(OrgDb = org.Hs.eg.db) %>%
    simplify(., cutoff = simplify_thr,
             by = "p.adjust") 
  
  
    GO <- enrich@result %>%
    
    dplyr::select(Description, GeneRatio, BgRatio, pvalue, qvalue, geneID, Count) %>% 
    tidyr::separate_rows(geneID, sep = "/") %>%
    dplyr::mutate(experimental = if_else(geneID %in% table$gene_names, 1, 0)) %>%
    dplyr::group_by(Description) %>%
    dplyr::mutate(exp = sum(experimental == 1)) %>%
    dplyr::mutate(ratio = exp / Count) %>%
    dplyr::arrange(desc(ratio), qvalue) %>%
    tidyr::separate(GeneRatio,
                    into = c("a", "b"),
                    sep = "/",
                    remove = FALSE) %>%
    tidyr::separate(BgRatio,
                    into = c("c", "d"),
                    sep = "/",
                    remove = FALSE) %>%
    dplyr::mutate(fold_enrichment = (as.numeric(a) / as.numeric(b)) /
                    (as.numeric(c) / as.numeric(d))) %>%
    dplyr::select(-c(a, b, c, d)) %>%
    dplyr::mutate(geneID_sperimental = if_else(experimental == 1, geneID, "")) %>%
    dplyr::mutate(geneID_predicted = if_else(experimental == 0, geneID, "")) %>%
    dplyr::select(-experimental) %>% #To improve.
    dplyr::ungroup() %>%
    tidyr::nest(gene_names = c(geneID_predicted, geneID_sperimental, geneID)) %>%
    tidyr::unnest_wider(gene_names)
  
  return(GO)
}


string_exp_int <- function(table) {
  
  gene_list <- table %>%
    dplyr::pull(gene_names)
  
  data <-
    rba_string_interactions_network(
      ids = gene_list,
      species = 9606,
      required_score = 400
    ) %>%
    dplyr::select(source = preferredName_A, target = preferredName_B, score) %>%
    dplyr::mutate(source_target = paste0(source, "_", target)) %>%
    dplyr::mutate(target_source = paste0(target, "_", source)) %>% 
    dplyr::distinct(source_target, .keep_all = TRUE)
  return(data)
}
```

```{r LIMMA analysis}
interactors <-
  string_find_interactors(table = limma_tibble, score = 400, limits = NULL) %>% #Trovo tutti i primi interattori della nostra lista sperimetnale
# interactors %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_interactors.txt")

dplyr::left_join(limma_tibble, by=c("source"="gene_names")) %>% 
  dplyr::left_join(protein_groups, by=c("target"="gene_names")) %>% 
  dplyr::select(-protein_i_ds)

nodes <- string_find_interactors(table = limma_tibble, score = 800, limits = NULL) %>%  dplyr::distinct(target) 

predicted_nodes <-
  predicted_node_table(predicted_table_interactors = interactors, table = limma_tibble) %>% 
  

  #Lista di tutti i nodi sperimentali e predetti

limma_all_predicted <- interactors %>% 
  dplyr::filter(score>=0.4) %>% 
  pull(target) #Pull di tutti i nodi predetti

stringdb_filtered<- human_string %>% 
  dplyr::filter(combined_score>=0.4) %>% 
  dplyr::mutate(int= if_else(source %in% limma_all_predicted & target %in% limma_all_predicted, 1, 0), source_target = paste0(source, "_", target),target_source = paste0(target, "_", source)) %>% 
  dplyr::filter(int==1) %>% 
  dplyr::rename(score=combined_score) %>% 
  unique() #Trovo le interazioni tra i nodi predetti da StringDB
  
limma_all <- interactors %>% 
  dplyr::bind_rows(stringdb_filtered)#Tabella finale con tutte le interazioni tra tutti i nodi sperimentali e predetti


limma_roc_filtered  %>% dplyr::filter(is.na(logFC)) %>% dplyr::distinct(source) %>% nrow()
  
  
corum <- corum_edges(predicted_list = predicted_nodes)


limma_roc_table <- roc_precision_data(corum_table = corum, string_predicted_interactors = limma_all)

roc_precision_graph(data = limma_roc_table, graph = "roc")


limma_roc_filtered <- limma_all %>% 
  dplyr::select(-int, -source_target, -target_source) %>% 
dplyr::filter(score>=0.8)


 # limma_all %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_all.txt")

limma_enrichment <- enrichment_table(predicted_table_interactors = interactors, thr = 0.8, simplify_thr = 0.7, table = limma_tibble)

# limma_enrichment %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_enrichment.txt")


limma_cluster <- read.csv(file = "/Users/giorgiacucina/Desktop/Phag+ESCRT filtered default  node.csv") %>% 
  dplyr::mutate(sperimental= if_else(is.na(adj_p_val), 0, 1)) %>% 
  dplyr::select(sperimental, name)

pred_node<- limma_cluster %>% 
  dplyr::filter(sperimental==0) %>% 
  dplyr::left_join(protein_groups, by=c("name"="gene_names")) %>% 
  dplyr::select(-protein_i_ds) %>% 
  dplyr::rename(gene_names=name) %>% 
  dplyr::mutate(logFC=NA) %>% 
  dplyr::select(gene_names, logFC, intensity, sperimental)
                
list<-limma_cluster %>% 
  dplyr::filter(sperimental==1) %>% pull(name)

complete_nodes_cluster <- limma_tibble %>% 
  dplyr::filter(gene_names %in% list) %>% 
  dplyr::select(gene_names, logFC) %>% 
  dplyr::mutate(intensity=NA, sperimental=1) %>% 
  bind_rows(pred_node) 

# complete_nodes_cluster %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_cluster_node.txt", quote = FALSE,sep = "\t", row.names = FALSE)



limma_int_cluster <- human_string %>% 
  dplyr::filter(combined_score>=0.8) %>% 
  dplyr::mutate(int= if_else(source %in% limma_cluster$name & target %in% limma_cluster$name, 1, 0)) %>% 
    dplyr::filter(int==1) %>% 
  dplyr::select(-int) %>% 
  tidyr::unite("stringID", source:target, remove = TRUE) %>% 
  dplyr::distinct(stringID, .keep_all = TRUE) %>% 
  dplyr::rename(score=combined_score) %>% 
tidyr::separate(stringID, c("source", "target")) %>% 
  dplyr::left_join(limma_tibble, by=c("source"="gene_names")) %>% 
  dplyr::left_join(protein_groups, by=c("target"="gene_names")) %>% 
  dplyr::select(-protein_i_ds) %>% 
  dplyr::mutate(sperimental= if_else(is.na(logFC), "N", "Y")) %>% 
  dplyr::select(source, target, score)
  
   # limma_int_cluster %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_cluster.txt", quote = FALSE,sep = "\t", row.names = FALSE)
```

```{r Perseus analysis}
interactors <-
  string_find_interactors(table = perseus)
# interactors %>% write.table(file = "/Users/giorgiacucina/Desktop/perseus_interactors.txt")

predicted_nodes <-
  predicted_node_table(predicted_table_interactors = interactors, table = perseus)

corum <- corum_edges(predicted_list = predicted_nodes)

perseus_roc_table <- roc_precision_data(corum_table = corum, string_predicted_interactors = interactors)

p1 <- roc_precision_graph(data = perseus_roc_table, graph = "roc")
p1

perseus_enrichment <- enrichment_table(predicted_table_interactors = interactors, thr = 0.9, simplify_thr = 0.7, table = perseus)

```

```{r BH analysis}
interactors <-
  string_find_interactors(table = welch_bh)

predicted_nodes <-
  predicted_node_table(predicted_table_interactors = interactors, table = welch_bh)

corum <- corum_edges(predicted_list = predicted_nodes)

bh_roc_table <- roc_precision_data(corum_table = corum, string_predicted_interactors = interactors)

p2<-roc_precision_graph(data = bh_roc_table, graph = "roc")
p2

bh_enrichment <- enrichment_table(predicted_table_interactors = interactors, thr = 0.9, table = welch_bh)

```

```{r GO}

 roc_filtered <- interactors %>% 
    dplyr::filter(score>=0.8) %>%
    dplyr::count(target) %>%
    pull(target)
  
  sperimental <- limma_tibble %>%
    pull(gene_names)
  
  nodes_predicted_all <- c(roc_filtered, sperimental)
  
  nodes_roc_filtered <- unique(nodes_predicted_all)
  

  
    
  enrich <-
    enrichGO(nodes_roc_filtered,
      OrgDb = org.Hs.eg.db,
      keyType= "SYMBOL",
      ont = "CC",
      pAdjustMethod = "BH",
      pvalueCutoff = 0.05
    ) %>%
    setReadable(OrgDb = org.Hs.eg.db) %>%
    simplify(., cutoff = 1,
             by = "p.adjust")
  
 test <- enrich@result %>%
    
   dplyr::select(Description, GeneRatio, BgRatio, pvalue, qvalue, geneID, Count) %>% #Aggiungere una colonna di size
   tidyr::separate_rows(geneID, sep = "/") %>%
   dplyr::mutate(experimental = if_else(geneID %in% limma_tibble$gene_names, 1, 0)) %>%
   dplyr::group_by(Description) %>%
   dplyr::mutate(exp = sum(experimental == 1)) %>%
   dplyr::mutate(ratio = exp / Count) %>%
   dplyr::arrange(desc(ratio), qvalue) %>%
   tidyr::separate(GeneRatio,
                   into = c("a", "b"),
                   sep = "/",
                   remove = FALSE) %>%
   tidyr::separate(BgRatio,
                   into = c("c", "d"),
                   sep = "/",
                   remove = FALSE) %>%
   dplyr::mutate(fold_enrichment = (as.numeric(a) / as.numeric(b)) /
                   (as.numeric(c) / as.numeric(d))) %>%
   dplyr::select(-c(a, b, c, d)) 
 
test2<- test %>%
   dplyr::select(-exp, -experimental) %>% 
   tidyr::nest(geneID = geneID) %>%
   tidyr::unnest_wider(geneID) %>%
   
 #   tidyr::hoist(.col = geneID,
 #                geneID_exp = "geneID")
 # tidyr::unnest_wider(geneID) %>%
   
   dplyr::mutate(geneID_exp = purrr::map(.x = geneID, ~ purrr::keep(.x, .x %in% limma_tibble$gene_names))) %>%
    dplyr::mutate(geneID_pred = purrr::map(.x = geneID, ~ purrr::keep(.x, !.x %in% limma_tibble$gene_names))) %>%

  dplyr::mutate(geneID_exp2 = purrr::map(.x = geneID_exp, ~ unlist(.x))) 
   # dplyr::mutate(geneID_exp= purrr::modify_if(geneID_exp, ~ length(.) == 0, 
  #   ~ list("NO")
  # )) %>% 
  #  dplyr::mutate(geneID_exp=  purrr::list_c(geneID_exp)) 
  # 
  # str()


test2$geneID_exp[333] %>% unlist()

 
    dplyr::mutate(geneID_sperimental = if_else(experimental == 1, geneID, "")) %>% 
    dplyr::mutate(geneID_predicted = if_else(experimental == 0, geneID, "")) %>%
    dplyr::select(-experimental) %>% #To improve.
    dplyr::ungroup() %>% 
    tidyr::nest(geneID = geneID) %>% 
    tidyr::unnest_wider(gene_names) %>% View()
    
    dplyr::mutate(geneID = stringr::str_replace_all("\\s+", "",geneID)) %>% 


    dplyr::mutate(experimental = sum(experimental == 1)) %>%
    dplyr::filter(experimental >= 1) %>%
    dplyr::ungroup() %>%
    tidyr::nest(gene_names = geneID) %>%
    dplyr::arrange(qvalue, experimental) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(gene_names = paste(gene_names, collapse = ",")) %>%
    dplyr::mutate(gene_names = stringr::str_replace_all(gene_names, ",", "")) %>% 
    dplyr::distinct(gene_names, .keep_all = TRUE) %>%
    dplyr::mutate(gene_names = stringr::str_replace_all(gene_names, "[()c\"]", ""))
  
```

```{r ROC curves}
library(patchwork)

p+p1 + theme(axis.text.y = element_blank(), axis.title.y = element_blank()) +plot_layout(guides = "collect")
```

```{r Limma only experimental}
limma_string <- string_exp_int(table = limma_tibble)
# limma_string %>% write.table(file = "/Users/giorgiacucina/Desktop/limma_string.txt")

corum_interactions <- corum_edges(predicted_list = limma_tibble %>%  pull(gene_names))

limma_sperimental_roc <- roc_precision_data(corum_table = corum_interactions, string_predicted_interactors = limma_string)
roc_precision_graph(data = limma_sperimental_roc, graph = "roc")


```

```{r CORUM interactors}
node_table <- function(table) {
  predict <- table %>%
    dplyr::count(target) %>%
    pull(target)
  
  sperimental <- table %>%
   dplyr::count(source) %>%
    pull(source)
  
  nodes_predicted_all <- c(predict, sperimental)
  
  nodes_predicted <- unique(nodes_predicted_all)
  
  return(nodes_predicted)
}

corum_nodes <- node_table(table=corum_interactions) %>% as.data.frame() %>% dplyr::mutate(gene_names= node_table(table=corum_interactions))
corum_predicted <- string_find_interactors(table = corum_nodes, score = 900)
# corum_predicted %>% write.table(file = "/Users/giorgiacucina/Desktop/corum_predicted.txt")

corum_limma_enrich <- enrichment_table(predicted_table_interactors = corum_predicted, thr = 0.4, simplify_thr = 0.7, table = corum_nodes)

```

```{r}

  
data <- limma_string %>%
      dplyr::mutate(
        corum = case_when(
          source_target %in% corum_interactions$source_target ~ 1,
          source_target %in% corum_interactions$target_source ~ 1,
          TRUE ~ 0
        )
      )
    
    df <- tibble::tibble()
    
    for (i in seq(from = 1, to = 0, by = -0.10)) {
      string_thr <- data %>%
        dplyr::mutate(thr = if_else(score >= i, "yes", "no")) #Vedo quali interazioni di String sono anche in CORUM (TP)
      
      for (j in 1:10) {
        set.seed(j)
        source <-
          sample(
            string_thr$source,
            size = sum(string_thr$corum == 1),
            replace = TRUE
          )
        target <-
          sample(
            string_thr$target,
            size = sum(string_thr$corum == 1),
            replace = TRUE
          )
        
        random_int <- cbind(source, target) %>%
          as.data.frame() %>%
          dplyr::left_join(human_string, by = join_by(source, target)) %>%
          dplyr::mutate(score = dplyr::if_else(is.na(combined_score), 0, combined_score)) %>% 
          dplyr::select(-combined_score)
        
        df_1 <-
          tibble::tibble(
                    TP = sum(string_thr$thr == "yes" & string_thr$corum == 1),
                    FN = sum(string_thr$thr == "no" & string_thr$corum == 1),
                    TPR = TP / (TP + FN),
                    FP = sum(random_int$score >= i),
                    TN = sum(random_int$score < i),
                    FPR = FP / (FP + TN),
                    STRINGSCORE = i,
                    fold = j
                  )  
        
        df <- rbind(df, df_1)
        
      }
    }
    
    
    df_final <- df %>%
      dplyr::mutate(P = TP / (TP + FP)) %>%
      dplyr::group_by(STRINGSCORE) %>%
      dplyr::summarise(
        FPR_mean = mean(FPR),
        FPR_sd = sd(FPR),
        TPR_mean = mean(TPR),
        TPR_sd = sd(TPR),
        P_mean = mean(P),
        P_sd = sd(P)
      ) 

```
